FROM dockerymh/hmtpbsa:gmx_openmpi_patch

ARG version=0.1.3
RUN pip install sh tqdm && \
    pip install --upgrade "dp-launching-sdk" -ihttps://repo.mlops.dp.tech/repository/pypi-group/simple

RUN source activate amber21 && \
    pip install sh && \
    pip install --upgrade "dp-launching-sdk" -ihttps://repo.mlops.dp.tech/repository/pypi-group/simple

COPY dist/unigbsa-$version.tar.gz /data/
RUN source activate amber21             && \
    cd /data/                           && \
    tar zxvf unigbsa-$version.tar.gz    && \ 
    cd unigbsa-$version                 && \
    python setup.py install             && \
    mkdir /app/                         && \
    cp launching /app/ -r               && \
    rm -rf /data/*


RUN echo `which python`
# COPY sources.list /etc/apt/sources.list
# RUN  sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
#RUN apt update -y
#RUN apt install -y vim

##RUN apt-get update \
# && apt-get install -y sudo

#RUN groupadd -g 1000 webshell
#RUN adduser --disabled-password --gecos '' --uid 1000 --gid 1000 webshell
#RUN adduser webshell sudo
#RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
