FROM dockerymh/hmtpbsa:gmx_openmpi_patch

ARG version=0.0.9.dev0
COPY hmtpbsa-$version.tar.gz /data/
RUN source activate amber21             && \
    cd /data/                           && \
    tar zxvf hmtpbsa-$version.tar.gz    && \ 
    cd hmtpbsa-$version                 && \
    python setup.py install             && \
    rm -rf /data/*

RUN echo `which python`
