FROM docker.io/dpzhengh/hmtpbsa:hmtpbsa-v1

SHELL ["conda", "run", "-n", "amber21", "/bin/bash", "-c"]

RUN conda activate amber21           && \
    pip install acpype               && \
    pip install gmx_MMPBSA==1.5.2    && \
    cp ./ /data/                     && \
    cd /data/                        && \ 
    python setup.py install          && \
    rm -rf /data/*
