name: MMPBSA unittest
on: [push]

jobs:
  MMPBSA_unittest:
    runs-on: "ubuntu-latest"
    container: dockerymh/ambertools21:latest
    
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
      
    - name: Setup enverioment
      shell: bash
      run: |
        conda init bash \
        && echo "conda activate amber21" >> ~/.bashrc
        source ~/.bashrc;
        conda install mdanalysis==2.0.0 gmx_MMPBSA pdb2pqr -c conda-forge
        
    - name: Install MMPBSA
      shell: bash
      run: |
        source ~/.bashrc
        python setup.py install;

    - name: Run unittest
      shell: bash
      run: |
        source ~/.bashrc
        cd tests;
        bash cmd.sh
