name: MMPBSA unittest
on: [push]

jobs:
  MMPBSA_unittest:
    runs-on: "ubuntu-latest"
    container: dpzhengh/hmtpbsa:hmtpbsa-v1
    
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
        
    - name: install hmtpbsa
      shell: bash
      run: |
        source activate amber21
        python setup.py install

    - name: run unittest
      shell: bash
      run: |
        source activate amber21
        cd tests
        bash cmd.sh
